sudo: false

before_install:
  - chmod +x gradlew
  - chmod +x .travis/deploy.sh

language: java

jdk:
  - oraclejdk7
  - oraclejdk8

deploy:
  - provider: script
    skip_cleanup: true
    script: ./.travis/deploy.sh $TRAVIS_TAG
    on:
      tags: true