sudo: false

before_install:
 - chmod +x gradlew

language: java

jdk:
 - oraclejdk7
 - oraclejdk8

 deploy:
   skip_cleanup: true
   provider: script
   script: ./.travis/deploy.sh $TRAVIS_TAG
   on:
     tags: true
